name: Build Development Docker image

on:
  workflow_dispatch:
  push:

env:
  IMAGE_BASE: freetakteam/ui
  IMAGE_TAG: :${{ github.ref_name }}
  IMAGE_SHA: ${{ github.sha }}
  OC_REGISTRY: ghcr.io

jobs:
  build_docker_image:
    name: Docker Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build the container image
      # can this be converted to podman at some point to be more foss?
      run: docker build . --file Dockerfile --tag $OC_REGISTRY/$IMAGE_BASE:$IMAGE_TAG --tag $OC_REGISTRY/$IMAGE_BASE:$IMAGE_SHA --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $OC_REGISTRY -u $ --password-stdin

    - name: Push image to registry
      run: |
        echo IMAGE_BASE=$IMAGE_BASE
        docker push $OC_REGISTRY/$IMAGE_BASE:$IMAGE_TAG
        docker push $OC_REGISTRY/$IMAGE_BASE:$IMAGE_SHA

